version: '3.7'
services:
 php:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: php7
  volumes:
   - ./site:/var/www/html
  ports:
   - 80:80
  depends_on:
   - mysql

 mysql:
  container_name: mysql
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: mysql
   MYSQL_DATABASE: my_db
   MYSQL_USER: user1
   MYSQL_PASSWORD: user1